### ISSUE TITLE
Run locally

### ISSUE THREAD

**Issue by CrashyBang** [ronreiter/interactive-tutorials#107]
How can I run the server locally, sorry have not done a lot of work with python but ver interested in what you have put together here, would love a chance to contribute!

Cheers,
Otis Wright.

**Comment by eyangs** [comment]
The server is not working now！
Maybe i can run it on my own server via the python inbuild httpd！
Dose anyone try it ？

**Comment by ronreiter** [comment]
I'll work on adding proper support and documentation for running the server locally.

**Comment by ichnaton** [comment]
For install on Linux Mint, the following worked:
```
sudo pip install flask
sudo pip install --upgrade pip
sudo pip install setuptools
sudo pip install flask
git clone https://github.com/ronreiter/interactive-tutorials.git
```
Run the webserver like:
python main.py  -d learnpython.org
