### ISSUE TITLE
Annoying ads

### ISSUE THREAD

**Issue by Ercaderca** [ronreiter/interactive-tutorials#13]
Hi, 

while I understand that you have to pay for the servers, lots of my readers felt repelled by the amount and style of ads on your website. Could you maybe revisit your web page marketing and transition to a less obtrusive model?

Kind regards
Eric

**Comment by MartinDesigner** [comment]
![imghome](https://cloud.githubusercontent.com/assets/13809960/9289329/0bef602c-436c-11e5-80fc-3ec07f82dd8d.jpg)
As a main point for everyone(!) I propose to try this amazing free app. Createer.com is an online software for easily designing online ads, responsive landing pages and print materials such as flyers, posters, covers, invitations and more. Createer lets you easily share your designs on social media, send them via email, download as HTML, image or PDF. Createer also includes 3,000 predesigned templates (browse here: https://beta2.createer.com/Templates?ghi) and over 250,000 images (illustrations, photos and icons) to work with in its user-friendly drag’n’drop enviroment. And finally this amazing stuff is here: https://beta2.createer.com/?ghi

**Comment by ronreiter** [comment]
Guys, I need to fund this free service somehow. Sorry.
