### ISSUE TITLE
Java Sphere Engine Console

### ISSUE THREAD

**Issue by motte** [ronreiter/interactive-tutorials#132]
The Java tutorial console is not working.  The gear animation appears in the output window when "Run," but nothing happens.

**Comment by DJviolin** [comment]
Same true to Python.

**Comment by mchlnix** [comment]
The fact that the Sphere Engine Widget has branding on it, means, that there are at max 70.000 submissions per month possible (more likely 10.000 or a prepaid model, that might not be recharged that often). Probably broken down to the individual sites. Also there is at best an allowed 25 submissions per minute.

So it could be, that Sphere Engine simply puts you in a queue to wait or doesn't display an error message, when it is busy/out of submissions.

More information on here: http://sphere-research.com/sphere-engine.html

**Comment by ronreiter** [comment]
Fixed.
