### ISSUE TITLE
Change python tutorial to match output and type of myfloat

### ISSUE THREAD

**Issue by nullhack** [ronreiter/interactive-tutorials#201]
My propose is to change the file: [Variables and types](https://github.com/ronreiter/interactive-tutorials/blob/master/tutorials/learnpython.org/en/Variables%20and%20Types.md) in order to match the variable type on output of the exercise (the variable is of the type float, but the output is required to be int):
#### Expected Output

String: hello Float: 10 Integer: 20
#### testing code

if mystring == "hello": print "String: %s" % mystring if isinstance(myfloat, float) and myfloat == 10.0: print "Float: %d" % myfloat if isinstance(myint, int) and myint == 20: print "Integer: %d" % myint
#### Expected Output

String: hello Float: 10.0 Integer: 20
#### testing code

if mystring == "hello": print "String: %s" % mystring if isinstance(myfloat, float) and myfloat == 10.0: print "Float: %0.1f" % myfloat if isinstance(myint, int) and myint == 20: print "Integer: %d" % myint

**Comment by ronreiter** [comment]
I see this is already fixed.
