### ISSUE TITLE
solution for perl loops exercise

### ISSUE THREAD

**Issue by HTRon** [ronreiter/interactive-tutorials#219]
I came up with a solution, and I saw the exercise said there was none and it asked that the solution be posted here.  Hopefully this is the correct place to post it!

For this solution, I needed to do a "USE INTEGER", which we haven't "learned" yet...so maybe that needs to be a lesson somewhere before this chapter?

    use integer;
    @numbers = (951,402,984,651,360,69,408,319,601,485,980,507,725,547,
                544,615,83,165,141,501,263,617,865,575,219,390,237,412,
                566,826,248,866,950,626,949,687,217,815,67,104,58,512,24,
                892,894,767,553,81,379,843,831,445,742,717,958,609,842,
                451,688,753,854,685,93,857,440,380,126,721,328,753,470,
                743,527);
    # write your code below
    $max = scalar @numbers;       
    for ($count=0 ; $count <= $max ; $count++)
    {
      $current = $numbers[$count];
      $count1 = $current / 2;
      if ($count1*2 == $current) {print $current, "\n";}
      if ($current == 237) {last;}
    }

**Comment by miparnisari** [comment]
This should be closed. There already is a solution, it works, and it is a lot simpler than the one posted here. https://github.com/ronreiter/interactive-tutorials/blob/master/tutorials/learn-perl.org/en/Loops.md#solution
