### ISSUE TITLE
Cannot see newly contributed page.

### ISSUE THREAD

**Issue by JohnKLawrence** [ronreiter/interactive-tutorials#244]
Ron:
I recently added an .md file for Java interfaces. I followed the contributor instructions and submitted a PR. It appears that you accepted the PR but I do not see the text when I navigate to https://www.learnjavaonline.org/en/Interfaces. 

Perhaps I missed a step. Please let me know.

**Comment by ronreiter** [comment]
Try now

- Ron


[image: Facebook] <http://www.facebook.com/ron.reiter> [image: Twitter]
<http://twitter.com/#!/ronreiter> [image: LinkedIn]
<https://il.linkedin.com/in/ronreiter>

**Comment by JohnKLawrence** [comment]
Much better. Thanks.
