### ISSUE TITLE
learn-c.org/de: No tutorials available

### ISSUE THREAD

**Issue by flooberleitner** [ronreiter/interactive-tutorials#245]
When you take a look at the German version of the website, there are no tutorials available (click a link in the TOC of the Welcome page and the tutorial comes up empty).
But there are German translations available in the repo.

After a quick look it seems the link text/target in the TOC links are mixed up.

I will try to submit a pull request in the next days.

**Comment by flooberleitner** [comment]
Hi @ronreiter,

I want to test my changes before submitting the pull request but I have troubles :/

What I have done so far:

- cloned my fork of the repo
- cd to local repo
- installed requirements with `pip install -r requirements.txt`
- started the webserver with `python main.py -d learn-c.org -p 8081`

When I open `localhost:8081` in the webbrowser I get a [KeyError](https://gist.github.com/anonymous/ce55e7243e80ff8a63f1e8414c66a9df)

I guess I would need to let the `learn-c.org` domain point to `localhost:8081` too, am I right?
Or is there an easier way? (Did not find any details on this in the Wiki/README/Website).

Best regards,
Flo

**Comment by ronreiter** [comment]
@flooberleitner you're doing everything right but I have a bug which I just fixed that did not allow working locally on anything other than port 5000. You can pull and do this again now.
