### ISSUE TITLE
learncs.org Basic Classes tutorial is not passable.

### ISSUE THREAD

**Issue by MaraJade** [ronreiter/interactive-tutorials#248]
The solution code gives this error:

```
prog.cs(3,24): error CS0542: `Main.Main()': member names cannot be the same as their enclosing type
prog.cs(2,14): (Location of the symbol related to previous error)
Compilation failed: 1 error(s), 0 warnings
```

Changing one of the "Main"s to something else doesn't allow you to pass.

**Comment by buttshark** [comment]
I can fix this! The reason it's throwing an error is because the compiler gets confused between the main class on line 7 and the main method on line 8. So, the class with the main method should have a name other than "Main".

**Comment by ronreiter** [comment]
@buttshark go ahead and send a PR :) don't have much time nowadays...
