### ISSUE TITLE
Going graphical

### ISSUE THREAD

**Issue by albfan** [ronreiter/interactive-tutorials#249]
Do you think it's out of scope to try to learn gtk with your tutorials

Glue will be broadway http://worldofgnome.org/running-gtk-apps-on-web-with-node-broadway/

Would be really amazing to learn basic from Gtk on an interactive web tutorial

https://www.gtk.org/documentation.php

**Comment by ronreiter** [comment]
That's a good question... I can't think of how to actually do this.

- Ron


[image: Facebook] <http://www.facebook.com/ron.reiter> [image: Twitter]
<http://twitter.com/#!/ronreiter> [image: LinkedIn]
<https://il.linkedin.com/in/ronreiter>

**Comment by albfan** [comment]
I just download repo and doing:

    python -d learn-c.org

I have it on localhost:5000

So I copy learn-c.org to learn-gtk.org in tutorials and add LEARNGTK_DOMAIN etc on constants.py

Let's see if I can make this work. It will need a broadway server running. You can try yourself:

     broadwayd &
     GDK_BACKEND=broadway gedit

on http://127.0.0.1:8080 you will see gedit ready to use

Don't know if this can be done with flask

This is an example on php-gtk http://gtk.php.net/

https://www.phpclasses.org/blog/post/162-Using-PHPGTK-to-serve-Web-Applications-to-HTML-5-Browsers.html

Can you figure out the details with this. I can ask on flask how this can be supported

I did a check and broadwayd is on libgtk3-bin package (Do you have it avaliable on your distro deploy?

**Comment by ronreiter** [comment]
The problem is that a web interface does not support any type of rendering
or verification mechanism based on a UI. It's just not possible to do this
interactively without implementing a really smart visual emulator for that.

- Ron


[image: Facebook] <http://www.facebook.com/ron.reiter> [image: Twitter]
<http://twitter.com/#!/ronreiter> [image: LinkedIn]
<https://il.linkedin.com/in/ronreiter>

**Comment by albfan** [comment]
Yes. That's a pity.

I guess the idea is to see result on screen, more than really check if user implements a solution.

If you ever plan to work on this let me know. I will close by  now
