### ISSUE TITLE
learnjavaonline - Server returns 500

### ISSUE THREAD

**Issue by Ph3n1x** [ronreiter/interactive-tutorials#296]
Steps to reproduce:
1. Open http://www.learnjavaonline.org/en/Hello%2C_World%21
2. Click on the first **Execute Code** button
3. Infinite **Executing, please wait...**

When you watch the network traffic, you see that the POST request results in a 500 Internal Server Error.

**Comment by ronreiter** [comment]
My account was disabled. Currently solving. This is not a code issue.
