### ISSUE TITLE
learn-c while loops

### ISSUE THREAD

**Issue by louisjamesmasi** [ronreiter/interactive-tutorials#305]
there is a problem this code it should print 6 as well but the expected output doesn't agree.

#include <stdio.h>

int main() {
    int array[] = {1, 7, 4, 5, 9, 3, 5, 11, 6, 3, 4};
    int i = 0;

    while (i < 10) {
        if(array[i] < 5){
            i++;
            continue;
        }

        if(array[i] > 10){
            break;
        }

        printf("%d\n", array[i]);
        i++;
    }

    return 0;
}

**Comment by GregN94** [comment]
This code won't print 6. Break in 14 line will disrupt while loop, end program will end at checking number 11. If you wont to print number 6 you should change break in 14 to the same lines as in first 'if':
`i++;
continue;`

**Comment by louisjamesmasi** [comment]
Exactly the tutorial is broken.

**Comment by r-pai** [comment]
The tutorial is not broken.  Please read the Exercise correctly. The 2nd point of exercise says "If the current number which is about to printed is greater than 10, don't print it and stop the loop." and that whats the code does. The loop is stoped when number greater that 10.

Question
_The array variable consists of a sequence of ten numbers. Inside the while loop, you must write two if conditions, which change the flow of the loop in the following manner (without changing the printf command):

If the current number which is about to printed is less than 5, don't print it.
**If the current number which is about to printed is greater than 10, don't print it and stop the loop.**_
