### ISSUE TITLE
Switch to Uniter for running PHP

### ISSUE THREAD

**Issue by olberger** [ronreiter/interactive-tutorials#312]
As an alternative to using Sphere engine, it seems possible to execute PHP code directly in the browser, requiring no server-side service to execute PHP.

Uniter seems one such environment: https://github.com/asmblah/uniter

See https://asmblah.github.io/uniter/demo/interactive.html for instance.

I guess that for the kind of PHP that's needed for this tutorial, that'd do the trick.

Of course, that would make a specific variant compared to other tutorials.

**Comment by ronreiter** [comment]
I want to find something that supports the same API for all different languages, not just PHP. It's just too much work for each.
