### ISSUE TITLE
INTERNAL SERVER ERROR

### ISSUE THREAD

**Issue by robocyber** [ronreiter/interactive-tutorials#319]
The original url for learn python homepage is https://www.learnpython.org/en/Hello%2C_World%21 .
However if I manipulate it to https://www.learnpython.org/en/Hello%2C_Wdfdforld%21 by putting any random variables in between; the site will give internal server error.

I believe it should efficiently  filter the user input. :)

**Comment by victor-ru** [comment]
This commit should fix it https://github.com/ronreiter/interactive-tutorials/commit/819e22da25d6c475ae982aac87053a9f72bd455a
