### ISSUE TITLE
Output in Java tutorial (https://www.learnjavaonline.org/en/Loops) is wrong. 

### ISSUE THREAD

**Issue by jrfarah** [ronreiter/interactive-tutorials#321]
I reference this part of the page:

```
int i;
for (i = 0; i < 5; i++) {
    if (i >= 3) {
        break;
    }
    System.out.println("Yuhu");
    if (i >= 1) {
        continue;
    }
    System.out.println("Tata");
}
System.out.println(i);
// Output
// Yuhu
// Tata
// Yuhu
// Yuhu
// 3
```

This output is wrong as best as I can tell. Because the second `if` statement is `>=' and not just `==`, the program should continue to print out "Tata" until the loop breaks.

EDIT: I see my mistake, @shinhacker 's explanation below was very helpful.

**Comment by shinhacker** [comment]
The Output is Correct there is no problem in the code also.

The "continue" main purpose is to "just continue the loop" or go next iteration skip rest i.e 
when i=0 
         It will print "Yuhu"
         since the (i>=1) is false because i=0
         the if statement would not be executed
         the System.out.println("Tata") //this would be executed
         so next output is "Tata"
when i=1
         Again it would print "Yuhu" // the previous if() condition is still false (i>=3)
          now i=1 so (i>=1) is true
           and since continue is used "all the statements written after this inside the for loop is skipped it 
            basically goes to next iteration"
 
so my i=2
        the result will be same as above (when 'i' was 1 )

when i=3
          it "Breaks out of the loop" because break statement  is used.

as soon as it breaks when i=3 it gets out of loop the value of i is still 3 (i=3)

so the final output statement 
print value of i // i.e 3


Conclusion :  The Output of Java Tutorial (https://www.learnjavaonline.org/en/Loops) is ## **NOT** wrong

**Comment by jrfarah** [comment]
@shinhacker thank you for the explanation. I just started learning Java so this helped a lot.
