### ISSUE TITLE
Deploying Updates

### ISSUE THREAD

**Issue by meech-ward** [ronreiter/interactive-tutorials#325]
Hi @ronreiter. Are changes to the tutorials on `master` automatically deployed?

A pull request of mine was merged in recently https://github.com/ronreiter/interactive-tutorials/pull/324 but the changes haven't appeared on <learn-c.org>. I just want to make sure that I didn't make a mistake or if it just takes a while before the changes get deployed.

**Comment by ronreiter** [comment]
I deploy them manually. I can get a CI/CD pipeline up but I don't think it's needed now.
