### ISSUE TITLE
Java tutorial solution, Variables_and_Types

### ISSUE THREAD

**Issue by Aaahh** [ronreiter/interactive-tutorials#33]
The solution is incorrect. You must put (float) in 
        float e = 2.0;
like
        float e = (float)2.0;
The real solution is 
public class Main {
    public static void main(String[] args) {
        byte zero = 0;
        short a = 3;
        int b = 1;
        char d = ' ';
        float e = (float)2.0;
        boolean f = true;
        String output = "H" + a + b + b + zero + d + "w" + zero + "r" + b + "d" + d + e + d + f;
        System.out.println(output);
    }
}

**Comment by Aakarshak1** [comment]
If this issue is resolved then you should close it.
It is still open.
