### ISSUE TITLE
Inconsistent syntax highlighting in examples and terminal

### ISSUE THREAD

**Issue by sunnyeyez123** [ronreiter/interactive-tutorials#370]
The example code and the sample code in the terminal are highlighted differently. When going through this tutorial I wasn't confident that my code was correct as the colors for strings and keys didn't match.

<img width="335" alt="screen shot 2019-03-07 at 9 43 01 pm" src="https://user-images.githubusercontent.com/933590/54010190-a1c13c80-4122-11e9-8636-895b0d140e87.png">

**Comment by ronreiter** [comment]
Don't think it's worth working towards this as much as it would be nice.
