### ISSUE TITLE
Page not found link to  https://www.le.ac.uk/

### ISSUE THREAD

**Issue by govza** [ronreiter/interactive-tutorials#372]
In learn-c.org
https://github.com/ronreiter/interactive-tutorials/blob/master/tutorials/learn-c.org/en/Arrays%20and%20Pointers.md

`You may go through Pointers and Arrays for a further detailed discussion on this topic.`

Not found external link to Pointers and Arrays https://www.le.ac.uk/users/rjm1/cotter/page_59.htm

**Comment by imba-tjd** [comment]
This was fixed.
