### ISSUE TITLE
learn-js | Manipulating Arrays | Splicing

### ISSUE THREAD

**Issue by Vitaliy-B** [ronreiter/interactive-tutorials#375]
http://www.learn-js.org/en/Manipulating_Arrays
Splicing exercise works differently from what written in tutorial (I'm using Chrome)

![image](https://user-images.githubusercontent.com/3762223/55076082-32919500-509d-11e9-9980-8240dec64be7.png)

**Comment by lianglc** [comment]
Instruction is to remove the **five numbers** from the following array beginning from the 3rd index
removing fix numbers should use `myArrary.splice(3,5)` instead of 7 as seven numbers.
