### ISSUE TITLE
Python "Your session has been disconnected."

### ISSUE THREAD

**Issue by MichaelJCole** [ronreiter/interactive-tutorials#397]
https://www.learnpython.org/en/Hello%2C_World%21

Hi, I got that error message whenI clicked "Run" on the first example.

Also, it's not clear that DataCamp's "Free Tutorial" (which comes with a 40% discount) is actually not part of your site!  It took me a minute to realize you had more content here.

Thanks!

**Comment by bakera81** [comment]
Hi @MichaelJCole, I was unable to reproduce. All the chunks seemed to be working for me on that page. If you refresh the page, does it still cause problems? If so, please send some screenshots of the error.

**Comment by JOYCE-FRED** [comment]
Hi, I got the error **Your session has been disconnected** on [learnpython.org](url) when i try to run.
Also, if i hover my mouse on the run it says "session inactive" and i dont know why i am experiencing this issue.

**Comment by JOYCE-FRED** [comment]
> Hi @MichaelJCole, I was unable to reproduce. All the chunks seemed to be working for me on that page. If you refresh the page, does it still cause problems? If so, please send some screenshots of the error.

@bakera81 I am expereincing the same issue and i have refreshed several times still giving me the same error

**Comment by joel-krueger** [comment]
I was still experiencing this.  I was able to resolve it by clearing the cookies for the website and refreshing.
