### ISSUE TITLE
run C++, it just says "Executing, please wait..."

### ISSUE THREAD

**Issue by ScottHutchinson** [ronreiter/interactive-tutorials#402]
Learn C++ - Free Interactive C++ Tutorial: http://learnpython.org/#.XQErDqTW3ng.twitter …

I'm trying this site for the first time.
When I try to run C++, it just says "Executing, please wait..."

And mail to support@learn-cpp.org was undeliverable.

https://twitter.com/ScottHutchFP/status/1138849050558525441

**Comment by krubokrubo** [comment]
I have the same problem. To add another diagnostic detail:

1. Open https://www.learn-cpp.org/en/Hello%2C_World! using Firefox (or Chrome)
2. Open the web console
3. On the page, click "Start Exercise" (the exercise appears)
4. On the page, click "Run"
Result: Web console shows:   `TypeError: string is undefined         codemirror.js:5093:24`
and the Output window just says "Executing, please wait..."

**Comment by anishh2003** [comment]
I have the same problem still. Is there a fix ?

**Comment by ronreiter** [comment]
Fixed
