### ISSUE TITLE
Minor typo in the Defining Variables section of `learn-c.org`.

### ISSUE THREAD

**Issue by carlsmith** [ronreiter/interactive-tutorials#408]
The first line currently looks like this:

    int a = 0,b = 1,c = 2,d = 3, e = 4;

The whitespace is inconsistent (before the `e` assignment).

**Comment by muj-programmer** [comment]
> The whitespace is inconsistent (before the `e` assignment).

@carlsmith could you please provide the exercise name in which you found this issue.
