### ISSUE TITLE
Python 3 compatibility

### ISSUE THREAD

**Issue by bkmgit** [ronreiter/interactive-tutorials#418]
Would be good to upgrade server code to use Python 3 since support for Python 2 ends soon https://python3statement.org/.  Issue #327 is related.

**Comment by ronreiter** [comment]
@victor-ru can you take this?

**Comment by r-pai** [comment]
Hi @ronreiter ,

Migrated the server code to python 3. 
The master branch **https://github.com/r-pai/interactive-tutorials** has the Changes.
Tested with my limited functionality knowledge. Most of the thing seems working , but I would need help in testing this.

My suggestion here is , we can create a new python3 branch and start testing this.
Let me know how you want to take this further.

**Comment by victor-ru** [comment]
@ronreiter can help here, please let me know if it's still relevant

**Comment by ronreiter** [comment]
@victor-ru please create a new Python3 branch and take @r-pai 's relevant code.
@r-pai please update your branch, I made a lot of recent changes.
Thanks!

**Comment by r-pai** [comment]
@ronreiter I have merged your changes and migrated the code from python 2to3.
@victor-ru , Please let me know when you create the new Python3 branch, I will create a pull request.

**Comment by kenttw** [comment]
Hi @ronreiter i have fix some bugs for python3 compatibility
at here https://github.com/kenttw/interactive-tutorials . could you merge this version to your main line ?

**Comment by kenttw** [comment]
and i have also test this version that could deployed to google app engine . I think if this platform could be easy deployed for everyone then it will be more and more popular XD.
this is my site at google app engine . site link is https://learning-dot-kent-tw.appspot.com/

**Comment by ronreiter** [comment]
@victor-ru want to give this another go?

**Comment by victor-ru** [comment]
@ronreiter sure, will do!
