### ISSUE TITLE
Learn-c.org tutorials use g++ rather than gcc

### ISSUE THREAD

**Issue by ashok-arora** [ronreiter/interactive-tutorials#426]
While working on the [Dynamic Allocation](https://www.learn-c.org/en/Dynamic_allocation) exercise, I realized that malloc has to be cast for c++ and not for c, but it still gave me an error. Also, the file is saved as prog.cpp thus triggering the g++ compiler. Could you rectify this as soon as possible?

**Comment by r-pai** [comment]
_malloc_ returns a pointer of void which needs be casted into pointers of any form.
Its the same in case of c and c++.

The solution in Dynamic Allocation exercise in C is wrong and also the tutorial needs change where malloc is explained.

In the solution 
mypoint = (point*)malloc(sizeof(point));

**Comment by ronreiter** [comment]
Already fixed
