### ISSUE TITLE
C Binary trees code does not compile

### ISSUE THREAD

**Issue by johanna-bodnyk** [ronreiter/interactive-tutorials#434]
The provided code for the C Binary Trees lesson (https://www.learn-c.org/en/Binary_trees) does not compile. It is intended to be complete as-is as far as I can tell, implementing in-order DFS. The user is meant to change it to pre-order DFS. Running the code as provided, as well as after changing to pre-order, gives the following error: 

```
prog.cpp: In function ‘int main()’:
prog.cpp:17:30: error: invalid conversion from ‘void*’ to ‘node_t* {aka node*}’ [-fpermissive]
   node_t * test_list = malloc(sizeof(node_t));
                        ~~~~~~^~~~~~~~~~~~~~~~
prog.cpp: In function ‘void insert(node_t*, int)’:
prog.cpp:50:28: error: invalid conversion from ‘void*’ to ‘node*’ [-fpermissive]
         tree->left = malloc(sizeof(node_t));
                      ~~~~~~^~~~~~~~~~~~~~~~
prog.cpp:68:29: error: invalid conversion from ‘void*’ to ‘node*’ [-fpermissive]
           tree->right=malloc(sizeof(node_t));
                       ~~~~~~^~~~~~~~~~~~~~~~
```

The explanation in this lesson is also quite terse compared to the preceding lessons (which are excellent!) If I had not known what a binary tree was to begin with the page would not have really enlightened me, and I still had to go to Wikipedia to refresh my memory on traversal types. I'm not sure there are really any C-specific concepts exposed in this lesson. Perhaps it should be omitted?

**Comment by ronreiter** [comment]
Was already fixed. Deployed now. Thanks
