### ISSUE TITLE
time for learn-rust.org?

### ISSUE THREAD

**Issue by AddaxSoft** [ronreiter/interactive-tutorials#484]
I want to write tutorials as I'm learning rust, but I can't find the right folder for that. any reason why we don't have a rust folder yet?

**Comment by ronreiter** [comment]
Just bought learnrust.org so we can do one now. want to send a pull request?

**Comment by AddaxSoft** [comment]
That was quick! Let's do this ;-)

**Comment by AddaxSoft** [comment]
pull request is waiting for your approval 👯 
Can you accept and attach to the new domain?

**Comment by ronreiter** [comment]
Connected
