### ISSUE TITLE
Solutions

### ISSUE THREAD

**Issue by DiegoGonL** [ronreiter/interactive-tutorials#489]
Hi, so I'm learing python using yout course (love it btw).
I made some solutions for the spanish version, how can I add them or contribute with it?

**Comment by AddaxSoft** [comment]
check out the contribution page: https://github.com/ronreiter/interactive-tutorials/blob/master/tutorials/Contributing%20Tutorials.md

tl;dr: fork the project, create your page and send a pull request for merging into master
