### ISSUE TITLE
[Question] How to run locally? 

### ISSUE THREAD

**Issue by nanoproductions** [ronreiter/interactive-tutorials#493]
I am wanting to contribute, but get stuck at the part of it not having clear instructions to running locally. 

Is there a virtual-env? or anything that I need to know of? 

Thanks!

**Comment by nobicycle** [comment]
Good question that I would like to have answered too. Does it run on Python3 is also something I'd like to know.

**Comment by nanoproductions** [comment]
I figured out how to run locally! I will be updating README to have it. Most likely send PR.

**Comment by nobicycle** [comment]
@nanoproductions 
Hey, don't get knocked over by a bus before that PR goes in :-)

**Comment by ronreiter** [comment]
I added a proper Dockerfile and a Makefile. Run make build && make run

**Comment by nobicycle** [comment]
> I added a proper Dockerfile and a Makefile. Run make build && make run

Thank you.
I have it running now.
On http://127.0.0.1:5000/en/Hello,_World! it is not really running localhost:

1. The top menus point to the internet. eg. https://www.learnsqlonline.org/
2. The code evaluation is done by https://www.datacamp.com/

Best wishes
