### ISSUE TITLE
Mistake in the "Map, Filter, Reduce" topic for Learn Python Course

### ISSUE THREAD

**Issue by rishitc** [ronreiter/interactive-tutorials#499]
Hi,
I was going through the ["Map, Filter, Reduce" topic](https://www.learnpython.org/en/Map,_Filter,_Reduce) on the learnpython.org course website, and I found that there is a mistake in the first subquestion of the final exercise of the topic.

According to the comments of the `script.py` file, we are supposed to round the numbers to _2 decimal places_, i.e. **2.456** becomes **2.46**, but in the `solution.py` file, the solution given rounds the numbers to _3 decimal places_. 
Also, I noticed that both solutions are accepted, which is quite unusual.

The expected answer according to the comments:
```python
# Use map to print the square of each number rounded
# to two decimal places
my_floats = [4.35, 6.09, 3.25, 9.77, 2.16, 8.88, 4.59]

# Expected Solution
map_result = list(map(lambda x: round(x**2, 2), my_floats))
```

The actual answer according to the `solution.py` file:
```python
# Use map to print the square of each number rounded
# to two decimal places
my_floats = [4.35, 6.09, 3.25, 9.77, 2.16, 8.88, 4.59]

# Actual Solution
map_result = list(map(lambda x: round(x ** 2, 3), my_floats))
```

---

### Solution given in Solution.py:
![Solution given in Solution.py](https://i.imgur.com/xJ3FUzw.png)

### What the solution should be... at least according to the comments given in the code:
![Actual solution according to the comments](https://i.imgur.com/rz0JRql.png)

I want to work on this issue and would request the maintainers to assign the issue to me, as I would like to work on the same.

Thank you,
Rishit

**Comment by nanoproductions** [comment]
This repo is for open source project, and I believe you can go ahead and just get started! If you are able to fix it yourself, then go ahead! If not, I'd be willing to take a swing at this.

**Comment by rishitc** [comment]
I'll take a swing at it first, then.

**Comment by rishitc** [comment]
I have corrected the question's description in the code's comments itself (English version of the tutorial). This should fix the problem.

Just waiting for the pull request to get accepted now.

**Comment by rishitc** [comment]
Hi,
Now that the fix has been pulled into the master branch, can this issue be closed now?
