### ISSUE TITLE
But on Learn-C miltidimensional array

### ISSUE THREAD

**Issue by millbj92** [ronreiter/interactive-tutorials#510]
Bug on Learn-C multidimensional array tutorial. The for loop iterating over j only looks for < 5. There are 5 elements in the array, meaning it should either be <= 5 or < 6.

**Comment by moneshsridhar** [comment]
Hi @millbj92 

Replying to
> Bug on Learn-C multidimensional array tutorial. The for loop iterating over j only looks for < 5. There are 5 elements in the array, meaning it should either be <= 5 or < 6.

I'm explaining you that,
Size of that array, **grades[2][5]**
**i** starts from 0 to 1,
**j** starts from 0 to 4 only. 
So its wrong when you write **j <= 5** or **j < 6** , it'll show **'Array index out of bounds'** error.
 
Iterating over j from **0 to 4** is correct and its not a **BUG**  
Happy coding ;)
