### ISSUE TITLE
Broken Icons

### ISSUE THREAD

**Issue by ahwm** [ronreiter/interactive-tutorials#516]
![image](https://user-images.githubusercontent.com/20478373/94176005-afe5c380-fe54-11ea-981c-38b91bace0d0.png)

I've seen this on all the sites I looked at. It looks like you're grabbing a wrong FontAwesome embed maybe?

![image](https://user-images.githubusercontent.com/20478373/94176072-cc81fb80-fe54-11ea-9181-b4c41770a82c.png)

**Comment by ronreiter** [comment]
Fixed
