### ISSUE TITLE
Markdown issue

### ISSUE THREAD

**Issue by rich1n** [ronreiter/interactive-tutorials#541]
There is an issue in the [Basic Operators - Spanish](https://www.learnpython.org/es/Basic%20Operators) final part; there's show the solution and the code example is written in the markdown and not in the code editor
![issue](https://user-images.githubusercontent.com/66102911/104829253-5f9dd180-5848-11eb-97a2-48dead23fc49.png)
.

**Comment by ronreiter** [comment]
Solved
