### ISSUE TITLE
Support starting local environment with a different domain (not learnpython.org)

### ISSUE THREAD

**Issue by ronreiter** [ronreiter/interactive-tutorials#633]
The make command needs to be able to support the DOMAIN argument so that 

`DOMAIN=learnjavaonline.org make dev`

would work

**Comment by ronreiter** [comment]
@shrn01 I finished this just now, please refer to the readme file

**Comment by shrn01** [comment]
Hey Ron, yeah I basically did this before within the dockerfile, and then scrapped it as I wasn't able to do it with Gunicorn.

So yeah this is just for dev environment, we don't need to care about production here, so no need for Gunicorn!!

**Comment by shrn01** [comment]
Hey Ron, yeah I basically did this before within the dockerfile, and then scrapped it as I wasn't able to do it with Gunicorn.

So yeah this is just for dev environment, we don't need to care about production here, so no need for Gunicorn!!

**Comment by ronreiter** [comment]
Correct. Gunicorn is only required in production, which is why the docker compose overrides the gunicorn command

**Comment by shrn01** [comment]
Yeah, here dockerfile and docker-compose are two different ways of running a docker container right, so i didn't get what you meant by `override gunicorn` before. Everything makes sense now!!
