### ISSUE TITLE
LearnPython Suggestion: Teach Input()

### ISSUE THREAD

**Issue by JamesC01** [ronreiter/interactive-tutorials#658]
I personally think the input function is an incredibly fundamental and useful function. I was surprised it wasn't mentioned on the site. I think it would be useful to introduce it early, and use it in multiple code examples on the site.

**Comment by ronreiter** [comment]
The problem is that it's hard to make it work with a web-based environment.

**Comment by adel3li** [comment]
I think you could at least mention it.
