### ISSUE TITLE
Hi, I want to contribute the following: Chinese Translation[learnpython.org]

### ISSUE THREAD

**Issue by PILIHU2022** [ronreiter/interactive-tutorials#764]
But I can't find the document location where the tutorial is located, please let me know, thank you

**Comment by dawnandrew100** [comment]
[Link to the tutorial](https://github.com/ronreiter/interactive-tutorials/tree/master/tutorials/learnpython.org)

[Contribution guidelines](https://github.com/ronreiter/interactive-tutorials/blob/master/tutorials/Contributing%20Tutorials.md)

[Tutorial Template](https://github.com/ronreiter/interactive-tutorials/blob/master/tutorials/MyFile.md)

**Comment by dawnandrew100** [comment]
> But I can't find the document location where the tutorial is located, please let me know, thank you

[Link to the tutorial](https://github.com/ronreiter/interactive-tutorials/tree/master/tutorials/learnpython.org)

[Contribution guidelines](https://github.com/ronreiter/interactive-tutorials/blob/master/tutorials/Contributing%20Tutorials.md)

[Tutorial Template](https://github.com/ronreiter/interactive-tutorials/blob/master/tutorials/MyFile.md)

**Comment by PILIHU2022** [comment]
> > But I can't find the document location where the tutorial is located, please let me know, thank you
> 
> [Link to the tutorial](https://github.com/ronreiter/interactive-tutorials/tree/master/tutorials/learnpython.org)
> 
> [Contribution guidelines](https://github.com/ronreiter/interactive-tutorials/blob/master/tutorials/Contributing%20Tutorials.md)
> 
> [Tutorial Template](https://github.com/ronreiter/interactive-tutorials/blob/master/tutorials/MyFile.md)

Thanks! But I think this repo might will NOT update:(
Because the pull requests are NOT merged for a long time.
