### ISSUE TITLE
Javascript Inheritance 

### ISSUE THREAD

**Issue by davidchase** [ronreiter/interactive-tutorials#99]
Great set of tutorials, only small comment
after you do:

```
Student.prototype = new Person(); // inherit Person
```

you should adjust the constructor to point to Student instead of Person

```
// correct the constructor pointer because it points to Person
Student.prototype.constructor = Student;
```

Maybe also show how to use the person constructor, and then how
student can inherit from that, instead of creating a init method...

**Comment by ronreiter** [comment]
@davidchase hey, mind sending me a pull request that explains why to do this as well?

**Comment by ronreiter** [comment]
Probably too old
